perfect_match_test_evaluator <- function(lst.tabs, alpha = 0.05) {
# the function takes a list contains data.frames generated by perfect_match_trials() and returns a data.frame
# that gives an estimate of type1 error rate, true positive rate(TPR) and false postie rate (FPR)
# argument:
# lst.tabs: a list contains real.index and two lists of data.frames generated by Wang's algrithm on simulated perfect match data, called null.tabs and alt.tabs.
# There is no dmr simulated in data used to generate null.tabs; clusters specified by real.index are generated as DMR for the data used for generate
# alt.tabs
#
#alpha: a positive number used to specify the signifcant level. Candidate DMRs specified in the data.frame with fwer less than alpha will be
# considered as a dmr identifeid by the algrithm.

  null.tabs <- lst.tabs[["null.tabs"]]
  alt.tabs <- lst.tabs[["alt.tabs"]]
  real.index <- lst.tabs[["real.index"]]

  # estimate the type-1 error rate by calculate average number of clusters being incorrectly identified as DMRs over total clusters generated
  alpha <- 0.05 # the threhold
  sample.N <- length(null.tabs) # how many trials run in total
  num.clusters <- length(cluster.lengths) # total number of clusters
  df.combined.null.tabs <- do.call(rbind, null.tabs)
  identified.0 <- df.combined.null.tabs[df.combined.null.tabs$fwerArea < alpha, ]
  type1.error <- nrow(identified.0) / (num.clusters * sample.N)

  # calculate average FPR and TPR. TPR is calculated as the proportion of DMRs correctely identified among all DMRs identified and
  # FPR is the proportion of DMRs incorrectly identified among all clusters that are not simulated as DMR.
  lst.power.estimate.of.trial <- lapply(alt.tabs, function(df) {
    df.identified.positive <- df[df$fwerArea < alpha, ]
    if (nrow(df.identified.positive) == 0) {
      tpr <- 0
      fpr <- 0
    } else {
      df.true.positive <- df.identified.positive[df.identified.positive$cluster %in% real.index, ]
      tpr <- nrow(df.true.positive) / nrow(df.identified.positive)
      fpr <- (nrow(df.identified.positive) - nrow(df.true.positive)) / (num.clusters - length(real.index))
    }
    return(c(tpr,fpr))
  })

  df.combined.power.estimate <- do.call(rbind, lst.power.estimate.of.trial)
  avg.estimate <- c(type1.error, colMeans(df.combined.power.estimate))
  names(avg.estimate) <- c("type1.error", "average.TPR", "average.FPR")
  return(avg.estimate)
}